### ISSUE TITLE
README IMAGES

### ISSUE THREAD

**Issue by devhkyu** [ChoiHyungKyu/Smart_Coordinator#3]
![Kaggle3](https://user-images.githubusercontent.com/44195740/70390630-f9713900-1a0f-11ea-8f26-1212a2f18536.jpg)

**Comment by ChoiHyungKyu** [comment]
![maskrcnn](https://user-images.githubusercontent.com/44195740/85226734-071e6700-b414-11ea-8eb3-057dd53abdba.png)
![dataflow](https://user-images.githubusercontent.com/44195740/85226735-0980c100-b414-11ea-8cd0-3420bffa162c.png)
![detailer](https://user-images.githubusercontent.com/44195740/85226737-0ab1ee00-b414-11ea-9f02-4fcc1fc7f387.png)

**Comment by devhkyu** [comment]
![maskrcnn](https://user-images.githubusercontent.com/44195740/85226795-54023d80-b414-11ea-9dc9-c21d0414fcf1.png)
![dataflow](https://user-images.githubusercontent.com/44195740/85226796-55cc0100-b414-11ea-9347-a20c48737b60.png)
![detailer](https://user-images.githubusercontent.com/44195740/85226797-56fd2e00-b414-11ea-9901-5e99f6a4f088.png)

**Comment by devhkyu** [comment]
![1](https://user-images.githubusercontent.com/44195740/85227054-b27beb80-b415-11ea-9e1f-6973d4a1046b.png)
![2](https://user-images.githubusercontent.com/44195740/85227055-b445af00-b415-11ea-9e0d-cd89a02d5f91.png)
![3](https://user-images.githubusercontent.com/44195740/85227056-b576dc00-b415-11ea-9375-cfdce0b93906.png)

**Comment by devhkyu** [comment]
![itembased](https://user-images.githubusercontent.com/44195740/85227838-b9f1c380-b41a-11ea-9d5e-63cf824b22e1.png)
![SSIM](https://user-images.githubusercontent.com/44195740/85227852-d7bf2880-b41a-11ea-9f4d-f56fb21d2a00.png)
![sim](https://user-images.githubusercontent.com/44195740/85227853-d988ec00-b41a-11ea-9536-e63ee9454739.png)
