### ISSUE TITLE
home image

### ISSUE THREAD

**Issue by ieesejin** [ChoiHyungKyu/Smart_Coordinator#6]

**Comment by ieesejin** [comment]
![intro](https://user-images.githubusercontent.com/44631043/85229609-b44dab00-b425-11ea-90fa-eff1ea4887e9.png)
![intro2](https://user-images.githubusercontent.com/44631043/85229610-b57ed800-b425-11ea-9431-556b2de5c165.PNG)
![motivation](https://user-images.githubusercontent.com/44631043/85229611-b6b00500-b425-11ea-8b8f-621fa5de598b.PNG)
![CNN](https://user-images.githubusercontent.com/44631043/85229613-b7489b80-b425-11ea-90bd-1d30c61e329d.png)
![image_preprocessing](https://user-images.githubusercontent.com/44631043/85229615-b7e13200-b425-11ea-8d60-fbb9a813d14c.png)

**Comment by ieesejin** [comment]
![1](https://user-images.githubusercontent.com/44631043/85229911-9719dc00-b427-11ea-9aa2-b3fe648d8598.PNG)

**Comment by JJangA9** [comment]
![member](https://user-images.githubusercontent.com/44634594/85230033-5f5f6400-b428-11ea-8841-279056517fed.png)
